---
# Base system utilities
base_packages:
  - bat
  - git
  - tar
  - zsh
  - htop
  - tree
  - wget
  - unzip
  - curl
  - lsd
  - gnome-tweaks
# Networking utilities
network_packages:
  - nmap
  - iperf3
  - net-tools
  - traceroute
# Python development
python_packages:
  - python3-pip
  - python3-venv
  - python3-psutil
# Virtualization packages
virtualization_packages:
  - bridge-utils
  - cloud-init
  - cloud-utils
  - genisoimage
  - libguestfs-tools
  - libvirt-clients
  - libvirt-daemon-system
  - libvirt-dev
  - qemu-kvm
  - qemu-utils
  - virtinst
  - virt-manager
