dotfiles_base_dest: "/home/{{ ansible_user }}"
dotfiles_items:
  - { src: ".bashrc", dest_suffix: ".bashrc" }
  - { src: ".zshrc", dest_suffix: ".zshrc" }
  - { src: ".zprofile", dest_suffix: ".zprofile" }
  - { src: "ruff/ruff.toml", dest_suffix: ".config/ruff/ruff.toml" }
  - { src: ".gitconfig", dest_suffix: ".gitconfig" }
  - {
      src: "vscode/settings.json",
      dest_suffix: ".config/Code/User/settings.json",
    }
  - { src: "ghostty/config", dest_suffix: ".config/ghostty/config" }
  - { src: "ssh/config", dest_suffix: ".ssh/config" }
  - { src: "starship/starship.toml", dest_suffix: ".config/starship.toml" }
  - { src: "nvim", dest_suffix: ".config/nvim" }
dotfiles_repo: "https://github.com/sydasif/dotfiles.git"
dotfiles_dest: "/home/{{ ansible_user }}/.dotfiles"
