dotfiles_base_dest: "/home/{{ ansible_user }}"
dotfiles_items:
  - { src: ".bashrc", dest_suffix: ".bashrc" }
  - { src: ".zshrc", dest_suffix: ".zshrc" }
  - { src: ".zprofile", dest_suffix: ".zprofile" }
  - { src: "ruff.toml", dest_suffix: ".config/ruff/ruff.toml" }
  - { src: ".gitconfig", dest_suffix: ".gitconfig" }
  - { src: "settings.json", dest_suffix: ".config/Code/User/settings.json" }
  - { src: "ghostty/config", dest_suffix: ".config/ghostty/config" }
dotfiles_repo: "https://github.com/sydasif/dotfiles.git"
dotfiles_dest: "/home/{{ ansible_user }}/.dotfiles"
